apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: insights-ingress-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: insights-ingress-go
    app.kubernetes.io/part-of: insights-ingress-go
  name: insights-ingress-go
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: insights-ingress-go
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: insights-ingress-go
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtap-hcc-pipeline-tenant/insights-ingress-go/insights-ingress-go@sha256:01456e88802a929553a6cb2e0d9d269ea8dd51c0726a7c02010164383854b77b
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
status: {}
